### ISSUE TITLE
Revisar categoria.extra() (Tira error que no reconoce el extra() )

### ISSUE THREAD

**Issue by ezecastiglione18** [ezecastiglione18/TPFinal#5]
https://github.com/ezecastiglione18/TPFinal/blob/2a001afa72a654d95778c2ced090b9a8460d94a5/src/main/scala/main.scala#L37

**Comment by juancuiule** [comment]
No lo reconoce porque arriba dice que categoría es `String` y los strings no tienen el método `extra`, tenes que tiparlo bien para que sepa que entiende ese método
